version: '3.7'
services:
    mariadb:
        image: mariadb
        command: ["--default-authentication-plugin=mysql_native_password"]
        ports:
            - "${MYSQL_PORT}:3306"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    postgres:
        image: postgres
        ports:
            - "${POSTGRES_PORT}:5432"
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DATABASE}
    memcached:
        image: memcached
        entrypoint:
            - memcached
            - -m ${MEMCACHED_MEMORY}
        expose:
            - "11211"
    redis:
        image: redis
        ports:
            - "${REDIS_PORT}:6379"
    php:
        build: docker/php-fpm
        ports:
            - "${PHP_PORT}:9001"
        expose:
          - "9002"
        volumes:
            - ./config/php-pool:/etc/php7/php-fpm.d:cached
            - ./apps/symfony:/var/www/symfony:cached
            - ./logs/symfony:/var/www/symfony/var/log:cached
        links:
            - mariadb
            - postgres
            - memcached
            - redis
        extra_hosts:
            - "docker-host.localhost:127.0.0.1"
    nginx:
        build: docker/nginx
        ports:
            - "${NGINX_PORT}:80"
        links:
            - php
        volumes:
            - ./config/nginx:/etc/nginx/conf.d:cached
            - ./config/sites:/etc/nginx/sites-enabled:cached
            - ./logs/nginx:/var/log/nginx:cached
            - ./apps/symfony:/var/www/symfony:cached
    elk:
        image: willdurand/elk
        ports:
            - "${ELK_PORT}:80"
        volumes:
            - ./docker/logstash:/etc/logstash:cached
            - ./docker/logstash/patterns:/opt/logstash/patterns:cached
            - ./logs/symfony:/var/www/symfony/var/log:cached
            - ./logs/nginx:/var/log/nginx:cached
    adminer:
        image: adminer
        restart: on-failure
        ports:
          - "${ADMINER_PORT}:8080"

    rabbitmq:
        image: rabbitmq:management
        environment:
            RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
            RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_DEFAULT_VHOST}
        ports:
            - "${RABBITMQ_MANAGEMENT}:15672"
            - "${RABBITMQ_PORT}:5672"
        labels:
            NAME: "rabbitmq1"